### ISSUE TITLE
app.workers doesn't create deployment

### ISSUE THREAD

**Issue by dreamci** [renoki-co/laravel-helm-demo#26]
Hello,

In .helm/laravel-values.yaml, there is a section called workers, it doesn't have any reference in templates. 

Does it have any function?

>  Run separate deployments (workers) that will long-live processes
> other than the PHP-FPM. Can be used for example to run queues or Laravel Horizon.
> Each worker will create a new deployment.

    workers:
    - name: queue

      # The command to run the process.
      command: php artisan queue:work --memory=64

Thanks

**Comment by rennokki** [comment]
The workers' section was removed and replaced with [renoki-co/laravel-worker](https://github.com/renoki-co/charts/tree/master/charts/laravel-worker) chart.

This project seems outdated. 👀 I'll give it a quick update.

**Comment by rennokki** [comment]
I have updated it: https://github.com/renoki-co/laravel-helm-demo/commit/7b7fa2add5d0d811562bd45ea63cf7399de74a58
